chatbook/chatapp/urls.py
from django.conf.urls import url, include
from .views import *
from .import views
from django.conf.urls.static import static

urlpatterns = [

url(r'^signup$', views.signup_user, name='signup'),
url(r'^login$', views.login_user, name='login'),
url(r'^logout$', views.logout_user, name='logout'),
url(r'^notification_pull$', views.notification_pull, name='notification_pull'),
url(r'^set_notification_counter$', views.set_notification_counter, name='set_notification_counter'),
url(r'^reset_notification_counter$', views.reset_notification_counter, name='reset_notification_counter'),
url(r'^inbox/(?P<uuid>[-\w]+)$', views.inbox, name='inbox'),
url(r'^save_message_sent$', views.save_message_sent, name='save_message_sent'),
url(r'^save_message_received$', views.save_message_received, name='save_message_received'),
url(r'^message_history$', views.message_history, name='message_history'),
url(r'^is_token_valid$', views.is_token_valid, name='is_token_valid'),
url(r'^pull_image$', PullImage.as_view()),
]

chatbook/chatbook/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('chatapp.urls', namespace="chatapp")),
]

chatbook/templates/chatbook_login.html
<html>
<head>
    <!-- Google Analytics -->

<script async src="https://www.googletagmanager.com/gtag/js?id=GA_TRACKING_ID"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-129417653-1');
</script>
    <!-- End Google Analytics -->

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<style>
.box {
    width: 500px;
    margin: 200px 0;
}

.shape1{
    position: relative;
    height: 150px;
    width: 150px;
    background-color: #0074d9;
    border-radius: 80px;
    float: left;
    margin-right: -50px;
}
.shape2 {
    position: relative;
    height: 150px;
    width: 150px;
    background-color: #0074d9;
    border-radius: 80px;
    margin-top: -30px;
    float: left;
}
.shape3 {
    position: relative;
    height: 150px;
    width: 150px;
    background-color: #0074d9;
    border-radius: 80px;
    margin-top: -30px;
    float: left;
    margin-left: -31px;
}
.shape4 {
    position: relative;
    height: 150px;
    width: 150px;
    background-color: #0074d9;
    border-radius: 80px;
    margin-top: -25px;
    float: left;
    margin-left: -32px;
}
.shape5 {
    position: relative;
    height: 150px;
    width: 150px;
    background-color: #0074d9;
    border-radius: 80px;
    float: left;
    margin-right: -48px;
    margin-left: -32px;
    margin-top: -30px;
}
.shape6 {
    position: relative;
    height: 150px;
    width: 150px;
    background-color: #0074d9;
    border-radius: 80px;
    float: left;
    margin-right: -20px;
    margin-top: -35px;
}
.shape7 {
    position: relative;
    height: 150px;
    width: 150px;
    background-color: #0074d9;
    border-radius: 80px;
    float: left;
    margin-right: -20px;
    margin-top: -57px;
}
.float {
    position: absolute;
    z-index: 2;
}

.form {
    margin-left: 145px;
}
</style>
</head>
<!------ Include the above in your HEAD tag ---------->
<body>
<div class="container">

        <br><br>        
        <center><h2 id="yourStyle"><span style='color: #4285f4'>C</span> <span style='color: #ea4335'>h</span> <span style='color: #fbbc05'>@</span> <span style='color: #4285f4'>t</span> <span style='color: #34a853'>B</span> <span style='color: #ea4335'>o</span><span style='color: #4285f4'>O</span><span style='color: #ea4335'>K</span><span><sub>  login</sub></span></h2></center>
<center>
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">

                <div class="box">                    
                    <div class="shape1"></div>
                    <div class="shape2"></div>
                    <div class="shape3"></div>
                    <div class="shape4"></div>
                    <div class="shape5"></div>
                    <div class="shape6"></div>
                    <div class="shape7"></div>
                    <div class="float">
                        <form class="form" method="post" action="{% url 'chatapp:login' %}">{% csrf_token %}
                            <div class="form-group">
                                <label for="username" class="text-white">Email:</label><br>
                                <input type="text" name="email" autocomplete="off" id="email" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-white">Password:</label><br>
                                <input type="password" name="password" autocomplete="off" id="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <span><input type="submit" name="submit" class="btn btn-info btn-md" value="Login"></span>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
</center>
    </div>
</body>
</html>

chatbook/templates/chatbook_signup.html
<html>
<head>
    <!-- Google Analytics -->

<script async src="https://www.googletagmanager.com/gtag/js?id=GA_TRACKING_ID"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-129417653-1');
</script>
    <!-- End Google Analytics -->

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<style>
.box {
    width: 500px;
    margin: 200px 0;
}

.shape1{
    position: relative;
    height: 594px;
    width: 484px;
    background-color: #0074d9;
    border-radius: 50px;
    float: left;
    margin-right: -70px;
}

.float {
    position: absolute;
    z-index: 2;
}

.form {
    margin-left: 145px;
}
</style>
</head>

<body>
<div class="container">

        <br><br>        
        <center><h2 id="yourStyle"><span style='color: #4285f4'>C</span> <span style='color: #ea4335'>h</span> <span style='color: #fbbc05'>@</span> <span style='color: #4285f4'>t</span> <span style='color: #34a853'>B</span> <span style='color: #ea4335'>o</span><span style='color: #4285f4'>O</span><span style='color: #ea4335'>K</span><span><sub>  signUp</sub></span></h2></center>

        <center><div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">

                <div class="box">                    
                    <div class="shape1"></div>
                    
                    <div class="float">
                        <form class="form" method="post" action="{% url 'chatapp:signup' %}">{% csrf_token %}
                            <div class="form-group">
                                <label for="first_name" class="text-white">First Name:</label><br>
                                <input type="text" name="first_name" id="first_name" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="last_name" class="text-white">Last Name:</label><br>
                                <input type="text" name="last_name" id="last_name" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="username" class="text-white">Username:</label><br>
                                <input type="text" name="username" id="username" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="email" class="text-white">Email:</label><br>
                                <input type="text" name="email" id="email" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-white">Password:</label><br>
                                <input type="password" name="password" id="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="mobile" class="text-white">Mobile:</label><br>
                                <input type="text" name="mobile" id="mobile" class="form-control">
                            </div>
                            <div class="form-group">

                                <input type="submit" style="margin-top:20;" name="submit" class="btn btn-info btn-md" value="SignUp">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        </center>
    </div>
</body>
</html>